version: '3.9'

services:
  db:
    image: mysql:8.4
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
     - db_data:/mysql:/var/lib/mysql
volumes: 
  db_data: